Add core functionality
DBM-German/DBM-German-Bot pull request #3
Opened 2022-07-18 21:45 UTC by ACertainCoder

This pr includes the help command (Hilfe) as well as core functionality of the bot.

TODO:
[x] Update init event
[x] Update embed event
[x] Add an event to display multiple pages in embeds
[x] Implement the help command

2022-07-19 20:32 UTC, ACertainCoder commented
Someone other than me should double-check, if this works without any issues.

2022-07-20 08:05 UTC, TheLeCrafter requested changes
Wenn ein Befehl keine Parameter besitzt, dann kann die Hilfe Nachricht nicht gesendet werden.

2022-07-21 07:22 UTC, TheLeCrafter requested changes
Bei /hilfe [befehl] wird der optionale Parameter "befehl" nicht beachtet. Man könnte diesen entweder komplett entfernen oder das ursprüngliche Verhalten hinzufügen

2022-07-22 07:01 UTC, TheLeCrafter approved these changes
Der Parameter wird erst in der Zukunft eingebaut. Dennoch ist der Befehl zur Zeit gut funktionierend.

2022-07-22 07:02 UTC, merged